### PR TITLE
Change orgname to lowercase

### PR DESCRIPTION
**Pull request by s1061123**

### CODE REVIEW

**Comment by phoracek** [comment]
@s1061123 it failed with

```
tests/tests.go:24:2: cannot find package "github.com/k8snetworkplumbingwg/kubemacpool/pkg/names" in any of:
```

Is that a chicken-egg issue or bug in the PR?

**Comment by s1061123** [comment]
As following, I've removed all old-name.
```
[tohayash@tohayash-srv kubemacpool]$ pwd
/home/tohayash/src/k8s-npwg/kubemacpool
[tohayash@tohayash-srv kubemacpool]$ grep K8sNetworkPlumbingWG . -r
```

Travis pulling repo by following command, hence I suppose it may be reason. I guess the fix in travis web config side, not `.travis.yml` side. Could you please take a look into it? (I don't have permission for that).

```
$ git clone --depth=50 https://github.com/K8sNetworkPlumbingWG/kubemacpool.git 
```

**Comment by phoracek** [comment]
@s1061123 I restarted the build and it seems to use lower-case now, let's see if it passes.

**Comment by s1061123** [comment]
@phoracek Thank you for retest! let'see...

**Pull request merged**
