### PR TITLE
unit tests: Add make check

### PR DESCRIPTION
**Pull request by oshoval**
**What this PR does / why we need it**:
In order to detect that we don't miss updating files,
with make generate, add make check to the unit tests job.

**Special notes for your reviewer**:

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by RamLavi** [comment]
can you push a tmp commit the messes with the fmt check for example?

**Comment by oshoval** [comment]
> can you push a tmp commit the messes with the fmt check for example?

checked locally that `make check` catch it, but np will test here as well

**Comment by oshoval** [comment]
reverted the manifests PR and it found it, removing the commit
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/k8snetworkplumbingwg_kubemacpool/365/pull-kubemacpool-unit-test/1505526700451041280#1:build-log.txt%3A126

**Comment by RamLavi** [comment]
Thanks @oshoval for checking this!
/lgtm
/approve

**Pull request merged**
