### PR TITLE
cluster: Allow kubevirtci tag overriding

### PR DESCRIPTION
**Pull request by oshoval**
**What this PR does / why we need it**:
It is helpful either manually or for example
when used from CNAO, to use same tag of the cluster that CNAO deployed.
Otherwise a kubevirtci tag mismatch can cause failures once running 
KMP e2e tests from CNAO.

**Special notes for your reviewer**:

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by oshoval** [comment]
/cc @RamLavi 
we need this (+ release once it is merged please)
so we can bump kubevirtci on CNAO
otherwise if the cluster kubevirtci tag CNAO deployed is different then the kubevirtci helper scripts that KMP uses
it can product failures.
with this small change, the tag CNAO uses will be also used whenever needed when CNAO runs KMP e2e tests

**Comment by oshoval** [comment]
need first to adapt bump-kubevirtci.sh

**Review by qinqon — APPROVED** [review]
/lgtm
/approve

**Comment by oshoval** [comment]
Thanks
Can you please create a patch release 0.43.1 on main so CNAO consume it ?
@phoracek @RamLavi @qinqon

It will be indeed nice when we implement mechanism to allow consuming non core related changes
by CNAO, i will work on it when i have time.

**Comment by RamLavi** [comment]
@oshoval you need to backport this to `release-0.43` first no?

**Comment by RamLavi** [comment]
> @oshoval you need to backport this to `release-0.43` first no?

oh my bad, we are already after CF on that stable branch.
This change will only affect U/S,  am I correct? 
And only the U/S dev env (i.e. the lanes etc..) right?

I still wonder why you would want to backport it to that stable branch

**Comment by oshoval** [comment]
> > @oshoval you need to backport this to `release-0.43` first no?
> 
> oh my bad, we are already after CF on that stable branch. This change will only affect U/S, am I correct? And only the U/S dev env (i.e. the lanes etc..) right? If the answer is yes to both of the above then I assume that backporting this change is safe enough to do without getting QE to approve it and all that, but I still wonder why you would want to backport it to that stable branch - It's going GA in a few days
> 
> Perhaps you meant you want to issue a new `main` release (which will be minor `0.44.0` IIUC)? - in that case I'm all forward

this change doesn't affect KMP at all (as it only allow external overriding the default value)
we just need a main release so CNAO can consume it (it will help CNAO, not KMP)
ye we can use 0.44.0 if 0.43.0 is stable, in any case since CNAO main watches KMP main, the release must be on main
Thanks

**Comment by RamLavi** [comment]
> can you please create new minor 0.44.0 on main ?

https://github.com/k8snetworkplumbingwg/kubemacpool/releases/tag/v0.44.0

**Comment by oshoval** [comment]
> > can you please create new minor 0.44.0 on main ?
> 
> https://github.com/k8snetworkplumbingwg/kubemacpool/releases/tag/v0.44.0

Thanks !

**Pull request merged**
