### PR TITLE
vendor, golang, Upgrade to golang 1.17

### PR DESCRIPTION
**Pull request by RamLavi**
**What this PR does / why we need it**:

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by oshoval — APPROVED** [review]
Thanks
worth to add please reason in the PR desc if any specific one

**Comment by RamLavi** [comment]
> Thanks worth to add please reason in the PR desc if any specific one

This is just a maintenance bump, there is no specific reason other than being compatible with other kubevirt components

**Comment by RamLavi** [comment]
> > Thanks worth to add please reason in the PR desc if any specific one
> 
> This is just a maintenance bump, there is no specific reason other than being compatible with other kubevirt components

I take it back, PR desc should be more informative. thanks!

**Pull request merged**
