### PR TITLE
Remove "app" from matchingLabels

### PR DESCRIPTION
**Pull request by qinqon**
**What this PR does / why we need it**:
When Deployments are upgraded they cannot change matchingLabels since
they are inmutable, this change remove the problematic label from
matchingLabels.

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by RamLavi — CHANGES_REQUESTED** [review]
don't we want to also add a unique label for cert-pod?

**Comment by qinqon** [comment]
> don't we want to also add a unique label for cert-pod?

We have already "control-plane: cert-manager", the problem was that after adding "commonLabel" to kustomize.yaml it also add that to deployment labelMatcher, so just removing that is enough.

**Pull request merged**
